//
// Created by Daniil Shabrov on 5/18/23.
//

#ifndef BOOKING_SERVICE_PROPERTYSSERVICE_HPP
#define BOOKING_SERVICE_PROPERTYSSERVICE_HPP


class PropertysService {

};


#endif //BOOKING_SERVICE_PROPERTYSSERVICE_HPP
