version: "3.9"
services:
  db:
    image: postgres:15.3
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "gbplf"
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg/data:/var/lib/postgresql/data
      - ./data/pg/conf:/etc/postgresql
  booking_service:
    build: "./booking_service"
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      - db
      - cds
  webapp_service:
    build: "./webapp"
    ports:
      - "80:80"
    depends_on:
      - db
      - booking_service
      - cds
  #content delivery service
  cds:
    build: "./content_delivery_service"
    ports:
      - "3000:8080"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./data/attachments:/var/www/cds/attachments
      - ./logs/cds:/var/log/nginx

