version: "3.9"
services:
  db:
    image: postgres:15.3
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "gbplf"
    ports:
      - "5432:5432"
  booking:
    build: "./booking_service"
    ports:
      - "8080:8080"
      - "8000:8000"
  webapp:
    build: "./webapp"
    ports:
      - "80:80"